formats: []

build:
  image: latest
  tools:
    python: "3.9"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
