version: 2

build:
  os: ubuntu-20.04
    tools:
      python: "3.9"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true

sphinx:
  builder: dirhtml
  fail_on_warning: true
